version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ADDR=server:8080
      - DIFFICULTY=5
      - SERVER_KEEP_ALIVE=10s
      - SERVER_DEADLINE=3s
    ports:
      - "8080:8080"
    networks:
      - wisdom-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - SERVER_ADDR=server:8080
      - CLIENT_REQUEST_COUNT=100
    networks:
      - wisdom-network
    depends_on:
      - server

networks:
  wisdom-network:
    driver: bridge
