version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    networks:
      - wisdom-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    environment:
      - SERVER_ADDRESS=server:8080
    networks:
      - wisdom-network
    depends_on:
      - server

networks:
  wisdom-network:
    driver: bridge
