name: build

on:
  push:
    branches: []
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
        id: go

      - name: build and test
        run: |
          go test -v -timeout=100s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "mocks" | grep -v "_mock" > $GITHUB_WORKSPACE/profile.cov

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest

      - name: submit coverage
        run: goveralls -coverprofile=$GITHUB_WORKSPACE/profile.cov -service=github
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          name: Set up QEMU
          uses: docker/setup-qemu-action@v3